name: Recovering secrets

# Requirements:
# 1) have a lost secret:
#    MY_LOST_SECRET is stored in the repo (replace it with the lost one)
# 2) define some additional secrets stored in the repository:
#    OPENSSL_PASSWORD = "your strong password"
#    OPENSSL_ITERATIONS = "52" <-- choose a high number

on:
  push:
  workflow_dispatch:

jobs:
  recover:
    name: Recover
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - env:
          MY_LOST_SECRET: ${{ secrets.MY_LOST_SECRET }}
          OPENSSL_PASSWORD: ${{ secrets.OPENSSL_PASSWORD }}
          OPENSSL_ITERATIONS: ${{ secrets.OPENSSL_ITERATIONS }}
        run: |
          echo "MY_LOST_SECRET (***)     = ${MY_LOST_SECRET}"
          echo "MY_LOST_SECRET (openssl) = $(echo "${MY_LOST_SECRET}" | openssl enc -e -aes-256-cbc -a -pbkdf2 -iter ${OPENSSL_ITERATIONS} -k "${OPENSSL_PASSWORD}")"
          echo "Copy the above value, and then execute locally:"
          echo "echo PASTE_HERE | openssl base64 -d | openssl enc -d -pbkdf2 -iter \$OPENSSL_ITERATIONS -aes-256-cbc -k \$OPENSSL_PASSWORD"
